### ISSUE TITLE
kenzo cannot run properly in Clozure CL

### ISSUE THREAD

**Issue by yoyostein** [gheber/kenzo#111]
I am using Clozure CL on Mac, tried to install kenzo using github.

I get the following error message upon trying out the first command in the documentation: (setf m23 (moore 2 3)).

Thanks for any help. I am very new to Lisp / Common Lisp.

1 > (ql:quickload :kenzo)
To load "kenzo":
  Load 1 ASDF system:
    kenzo
; Loading "kenzo"

(:KENZO)
1 > (setf m23 (moore 2 3)) 
> Error: Undefined function MOORE called with arguments (2 3) .
> While executing: CCL::CHEAP-EVAL-IN-ENVIRONMENT, in process Listener(4).
> Type cmd-/ to continue, cmd-. to abort, cmd-\ for a list of available restarts.
> If continued: Retry applying MOORE to (2 3).
> Type :? for other options.

**Comment by gheber** [comment]
All Kenzo functions are defined in a package called CAT. Please try ``(setf m23 (cat:moore 2 3))`` or do a ``(in-package "CAT")`` followed by ``(setf m23 (moore 2 3))``!

Also, I believe there's a regression in CCL 1.10. The Kenzo test suite works fine with CCL 1.9, but I've seen a lot of errors with CCL 1.10.

**Comment by yoyostein** [comment]
Thanks! Your suggestion worked perfectly:

1 > (in-package "CAT")
#<Package "CAT">
1 > (setf m23 (moore 2 3))
[K1 Simplicial-Set]

**Comment by gheber** [comment]
Enjoy!
