### ISSUE TITLE
not an issue

### ISSUE THREAD

**Issue by dimpase** [gheber/kenzo#126]
Hi, just looked at how far you went with this, and it looks really great. I am curious about details on jupyther notebooks...

**Comment by gheber** [comment]
We can set up a Hangout for sometime next week if you like and chat.

**Comment by dimpase** [comment]
One question in particular whether it would be possible to stick to Python2 in running this in a notebook; this might be needed for deployment on cloud.sagemath.com

**Comment by gheber** [comment]
No, unfortunately, [cl-jupyter](https://github.com/gheber/sphynx/issues/6) requires Python 3.
