### ISSUE TITLE
Add nickname KENZO to package CAT

### ISSUE THREAD

**Issue by phoe** [gheber/kenzo#135]
Today on `#lisp`:

```
11:01 < feynhat> I am trying to use this library called "kenzo", which I have installed via quicklisp.
11:01 < feynhat> How do I use its member functions?
11:01 < feynhat> I've read a few SO posts, and have tried (use-package :kenzo).
11:02 < feynhat> But I get this: "The name :KENZO does not designate any package."
```

Myself, it was highly confusing for me as a newcomer to this package that, for a system named `KENZO`, its main package is named `CAT`.

Would it be good to add `KENZO` as a nickname of package `CAT` to avoid that sort of confusion in the future?

**Comment by Alizter** [comment]
Kenzo is the name of a cat, but I agree, the documentation could use some
work.

**Comment by phoe** [comment]
As much as I understand and enjoy the wordplay with the naming, it does confuse people who come from the outside and therefore do not have the knowledge that Kenzo is the name of the cat.

**Comment by gheber** [comment]
Done in c840448.

**Comment by phoe** [comment]
Thanks!
