### ISSUE TITLE
asdf issue with clisp

### ISSUE THREAD

**Issue by dimpase** [gheber/kenzo#14]
on clisp, 
     
      (require "asdf")
      (require "kenzo")

breaks at
```
;; Compiling file /home/scratch/dimpase/kenzo/src/chain-complexes.lisp ...
ASDF could not load kenzo because 
IF: variable *CMBN-CONTROL* has no value
.

*** - IF: variable *CMBN-CONTROL* has no value
The following restarts are available:
USE-VALUE      :R1      Input a value to be used instead of *CMBN-CONTROL*.
STORE-VALUE    :R2      Input a new value for *CMBN-CONTROL*.
TRY-RECOMPILING :R3     Try recompiling chain-complexes
RETRY          :R4      Retry compiling component ("kenzo" "src" "chain-complexes").
ACCEPT         :R5      Continue, treating compiling component ("kenzo" "src" "chain-complexes") as having been successful.
ABORT          :R6      Abort main loop
Break 1 CAT[3]> 
```

If I choose :R2 and enter 't, the build succeeds, and tests pass. Indeed in cat-init.lisp *CMBN-CONTROL* is set to T, perhaps, this matters for clisp for some reason.

**Comment by gheber** [comment]
That's odd. I'm traveling this week and will have a look over the weekend.

**Comment by dimpase** [comment]
this might be due to some `#+clisp` that is scattered throughout the code. (I wonder if it can be 
cleaned out...)

**Comment by dimpase** [comment]
fixed by https://github.com/gheber/kenzo/pull/16

**Comment by dimpase** [comment]
works on a new ASDF (version 3)
