### ISSUE TITLE
`smith-test`failure

### ISSUE THREAD

**Issue by gheber** [gheber/kenzo#142]
```
Failure Details:
 --------------------------------
 ECHCM-KILL-EPI-H-INTR []: 
      Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {100463A6D3}>
Execution of a form compiled with errors.
Form:
  (CAT-9:RANDOM-MATRIX 2 2 10)
Compile-time error:
  during macroexpansion of (CAT-9:RANDOM-MATRIX 2 2 ...). Use *BREAK-ON-SIGNALS* to intercept.
 error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too few elements in (2 2 10) to satisfy lambda list (CAT-9::LINE-N CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..
 --------------------------------
 --------------------------------
 ECHCM-KILL-EPI-F-INTR []: 
      Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {1004637F43}>
Execution of a form compiled with errors.
Form:
  (CAT-9:RANDOM-MATRIX 5 5 10)
Compile-time error:
  during macroexpansion of (CAT-9:RANDOM-MATRIX 5 5 ...). Use *BREAK-ON-SIGNALS* to intercept.
 error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too few elements in (5 5 10) to satisfy lambda list (CAT-9::LINE-N CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..
 --------------------------------
 --------------------------------
 LIST-SMITH []: 
      Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {1004633933}>
Execution of a form compiled with errors.
Form:
  (CAT-9:RANDOM-MATRIX 4 5 10)
Compile-time error:
  during macroexpansion of (CAT-9:RANDOM-MATRIX 4 5 ...). Use *BREAK-ON-SIGNALS* to intercept.
 error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too few elements in (4 5 10) to satisfy lambda list (CAT-9::LINE-N CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..
 --------------------------------
 --------------------------------
 MINIMAL-TERM-TOP-LEFT1 []: 
      Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {1004630C03}>
Execution of a form compiled with errors.
Form:
  (CAT-9:RANDOM-MATRIX 4 5 10)
Compile-time error:
  during macroexpansion of (CAT-9:RANDOM-MATRIX 4 5 ...). Use *BREAK-ON-SIGNALS* to intercept.
 error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too few elements in (4 5 10) to satisfy lambda list (CAT-9::LINE-N CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..
 --------------------------------
 --------------------------------
 MINIMAL-TERM-TOP-LEFT []: 
      Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {100462DEA3}>
Execution of a form compiled with errors.
Form:
  (CAT-9:RANDOM-MATRIX 4 5 10)
Compile-time error:
  during macroexpansion of (CAT-9:RANDOM-MATRIX 4 5 ...). Use *BREAK-ON-SIGNALS* to intercept.
 error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too few elements in (4 5 10) to satisfy lambda list (CAT-9::LINE-N CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..
 --------------------------------
 --------------------------------
 MINIMAL-TERM []: 
      Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {100462B173}>
Execution of a form compiled with errors.
Form:
  (CAT-9:RANDOM-MATRIX 4 5 10)
Compile-time error:
  during macroexpansion of (CAT-9:RANDOM-MATRIX 4 5 ...). Use *BREAK-ON-SIGNALS* to intercept.
 error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too few elements in (4 5 10) to satisfy lambda list (CAT-9::LINE-N CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..
 --------------------------------
 --------------------------------
 COLUMN-MINUS-5 []: 
      Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {1004628A63}>
Execution of a form compiled with errors.
Form:
  (CAT-9:RANDOM-MATRIX 4 5 10)
Compile-time error:
  during macroexpansion of (CAT-9:RANDOM-MATRIX 4 5 ...). Use *BREAK-ON-SIGNALS* to intercept.
 error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too few elements in (4 5 10) to satisfy lambda list (CAT-9::LINE-N CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..
 --------------------------------
 --------------------------------
 COLUMN-MINUS []: 
      Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {1004625A23}>
Execution of a form compiled with errors.
Form:
  (CAT-9:RANDOM-MATRIX 3 4 10)
Compile-time error:
  during macroexpansion of (CAT-9:RANDOM-MATRIX 3 4 ...). Use *BREAK-ON-SIGNALS* to intercept.
 error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too few elements in (3 4 10) to satisfy lambda list (CAT-9::LINE-N CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..
 --------------------------------
 --------------------------------
 COLUMN-SWAP-5 []: 
      Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {1004623313}>
Execution of a form compiled with errors.
Form:
  (CAT-9:RANDOM-MATRIX 4 5 10)
Compile-time error:
  during macroexpansion of (CAT-9:RANDOM-MATRIX 4 5 ...). Use *BREAK-ON-SIGNALS* to intercept.
 error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too few elements in (4 5 10) to satisfy lambda list (CAT-9::LINE-N CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..
 --------------------------------
 --------------------------------
 COLUMN-SWAP []: 
      Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {10046205E3}>
Execution of a form compiled with errors.
Form:
  (CAT-9:RANDOM-MATRIX 3 4 10)
Compile-time error:
  during macroexpansion of (CAT-9:RANDOM-MATRIX 3 4 ...). Use *BREAK-ON-SIGNALS* to intercept.
 error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too few elements in (3 4 10) to satisfy lambda list (CAT-9::LINE-N CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..
 --------------------------------
 --------------------------------
 LINE-SWAP-5 []: 
      Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {100461DEA3}>
Execution of a form compiled with errors.
Form:
  (CAT-9:RANDOM-MATRIX 4 5 10)
Compile-time error:
  during macroexpansion of (CAT-9:RANDOM-MATRIX 4 5 ...). Use *BREAK-ON-SIGNALS* to intercept.
 error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too few elements in (4 5 10) to satisfy lambda list (CAT-9::LINE-N CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..
 --------------------------------
 --------------------------------
 LINE-SWAP []: 
      Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {100461B173}>
Execution of a form compiled with errors.
Form:
  (CAT-9:RANDOM-MATRIX 3 4 10)
Compile-time error:
  during macroexpansion of (CAT-9:RANDOM-MATRIX 3 4 ...). Use *BREAK-ON-SIGNALS* to intercept.
 error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too few elements in (3 4 10) to satisfy lambda list (CAT-9::LINE-N CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..
 --------------------------------
 --------------------------------
 COLUMN-OP-5 []: 
      Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {1004618A63}>
Execution of a form compiled with errors.
Form:
  (CAT-9:RANDOM-MATRIX 4 5 10)
Compile-time error:
  during macroexpansion of (CAT-9:RANDOM-MATRIX 4 5 ...). Use *BREAK-ON-SIGNALS* to intercept.
 error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too few elements in (4 5 10) to satisfy lambda list (CAT-9::LINE-N CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..
 --------------------------------
 --------------------------------
 COLUMN-OP []: 
      Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {1004615B43}>
Execution of a form compiled with errors.
Form:
  (CAT-9:RANDOM-MATRIX 3 4 10)
Compile-time error:
  during macroexpansion of (CAT-9:RANDOM-MATRIX 3 4 ...). Use *BREAK-ON-SIGNALS* to intercept.
 error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too few elements in (3 4 10) to satisfy lambda list (CAT-9::LINE-N CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..
 --------------------------------
 --------------------------------
 LINE-OP-5 []: 
      Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {1004613433}>
Execution of a form compiled with errors.
Form:
  (CAT-9:RANDOM-MATRIX 4 5 10)
Compile-time error:
  during macroexpansion of (CAT-9:RANDOM-MATRIX 4 5 ...). Use *BREAK-ON-SIGNALS* to intercept.
 error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too few elements in (4 5 10) to satisfy lambda list (CAT-9::LINE-N CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..
 --------------------------------
 --------------------------------
 LINE-OP []: 
      Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {1004610703}>
Execution of a form compiled with errors.
Form:
  (CAT-9:RANDOM-MATRIX 3 4 10)
Compile-time error:
  during macroexpansion of (CAT-9:RANDOM-MATRIX 3 4 ...). Use *BREAK-ON-SIGNALS* to intercept.
 error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too few elements in (3 4 10) to satisfy lambda list (CAT-9::LINE-N CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..
 --------------------------------
 --------------------------------
 CHCM-MTRX []: 
      Unexpected Error: #<TYPE-ERROR expected-type: ARRAY datum: 
========== MATRIX 0 row(s) + 1 column(s) =====
========== END-MATRIX>
The value 
========== MATRIX 0 row(s) + 1 column(s) =====
========== END-MATRIX is not of type ARRAY..
 --------------------------------
 --------------------------------
 MTRX-PRDC []: 
      Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {10045FF8F3}>
Execution of a form compiled with errors.
Form:
  (CAT-9:RANDOM-MATRIX 2 3 10)
Compile-time error:
  during macroexpansion of (CAT-9:RANDOM-MATRIX 2 3 ...). Use *BREAK-ON-SIGNALS* to intercept.
 error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too few elements in (2 3 10) to satisfy lambda list (CAT-9::LINE-N CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..
 --------------------------------
 --------------------------------
 LEFT-SUBMATRIX []: 
      Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {10045FD1E3}>
Execution of a form compiled with errors.
Form:
  (CAT-9:RANDOM-MATRIX 3 4 10)
Compile-time error:
  during macroexpansion of (CAT-9:RANDOM-MATRIX 3 4 ...). Use *BREAK-ON-SIGNALS* to intercept.
 error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too few elements in (3 4 10) to satisfy lambda list (CAT-9::LINE-N CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..
 --------------------------------
 --------------------------------
 COPY-MTRX []: 
      Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {10045FA533}>
Execution of a form compiled with errors.
Form:
  (CAT-9:RANDOM-MATRIX 3 4 10)
Compile-time error:
  during macroexpansion of (CAT-9:RANDOM-MATRIX 3 4 ...). Use *BREAK-ON-SIGNALS* to intercept.
 error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too few elements in (3 4 10) to satisfy lambda list (CAT-9::LINE-N CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..
 --------------------------------
 --------------------------------
 RANDOM-MATRIX []: 
      Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {10045F08B3}>
Execution of a form compiled with errors.
Form:
  (CAT-9:RANDOM-MATRIX 2 3 10)
Compile-time error:
  during macroexpansion of (CAT-9:RANDOM-MATRIX 2 3 ...). Use *BREAK-ON-SIGNALS* to intercept.
 error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too few elements in (2 3 10) to satisfy lambda list (CAT-9::LINE-N CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..
 --------------------------------
```

**Comment by sphyynx** [comment]
The file  SMITH.LISP is absent  from Kenzo-9, was present  in Kenzo-8.
The appropriate file in Kenzo-9 is NEW-SMITH.LISP.


Le 21/05/2019 02:17, Gerd Heber a écrit :
 > Failure Details:
 >  --------------------------------
 >  ECHCM-KILL-EPI-H-INTR []:
 >       Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {100463A6D3}>
 > Execution of a form compiled with errors.
 > Form:
 >   (CAT-9:RANDOM-MATRIX 2 2 10)
 > Compile-time error:
 >   during macroexpansion of (CAT-9:RANDOM-MATRIX 2 2 ...). Use 
*BREAK-ON-SIGNALS* to intercept.
 >  error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too 
few elements in (2 2 10) to satisfy lambda list (CAT-9::LINE-N 
CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..
 >  --------------------------------
 >  --------------------------------
 >  ECHCM-KILL-EPI-F-INTR []:
 >       Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {1004637F43}>
 > Execution of a form compiled with errors.
 > Form:
 >   (CAT-9:RANDOM-MATRIX 5 5 10)
 > Compile-time error:
 >   during macroexpansion of (CAT-9:RANDOM-MATRIX 5 5 ...). Use 
*BREAK-ON-SIGNALS* to intercept.
 >  error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too 
few elements in (5 5 10) to satisfy lambda list (CAT-9::LINE-N 
CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..
 >  --------------------------------
 >  --------------------------------
 >  LIST-SMITH []:
 >       Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {1004633933}>
 > Execution of a form compiled with errors.
 > Form:
 >   (CAT-9:RANDOM-MATRIX 4 5 10)
 > Compile-time error:
 >   during macroexpansion of (CAT-9:RANDOM-MATRIX 4 5 ...). Use 
*BREAK-ON-SIGNALS* to intercept.
 >  error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too 
few elements in (4 5 10) to satisfy lambda list (CAT-9::LINE-N 
CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..
 >  --------------------------------
 >  --------------------------------
 >  MINIMAL-TERM-TOP-LEFT1 []:
 >       Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {1004630C03}>
 > Execution of a form compiled with errors.
 > Form:
 >   (CAT-9:RANDOM-MATRIX 4 5 10)
 > Compile-time error:
 >   during macroexpansion of (CAT-9:RANDOM-MATRIX 4 5 ...). Use 
*BREAK-ON-SIGNALS* to intercept.
 >  error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too 
few elements in (4 5 10) to satisfy lambda list (CAT-9::LINE-N 
CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..
 >  --------------------------------
 >  --------------------------------
 >  MINIMAL-TERM-TOP-LEFT []:
 >       Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {100462DEA3}>
 > Execution of a form compiled with errors.
 > Form:
 >   (CAT-9:RANDOM-MATRIX 4 5 10)
 > Compile-time error:
 >   during macroexpansion of (CAT-9:RANDOM-MATRIX 4 5 ...). Use 
*BREAK-ON-SIGNALS* to intercept.
 >  error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too 
few elements in (4 5 10) to satisfy lambda list (CAT-9::LINE-N 
CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..
 >  --------------------------------
 >  --------------------------------
 >  MINIMAL-TERM []:
 >       Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {100462B173}>
 > Execution of a form compiled with errors.
 > Form:
 >   (CAT-9:RANDOM-MATRIX 4 5 10)
 > Compile-time error:
 >   during macroexpansion of (CAT-9:RANDOM-MATRIX 4 5 ...). Use 
*BREAK-ON-SIGNALS* to intercept.
 >  error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too 
few elements in (4 5 10) to satisfy lambda list (CAT-9::LINE-N 
CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..
 >  --------------------------------
 >  --------------------------------
 >  COLUMN-MINUS-5 []:
 >       Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {1004628A63}>
 > Execution of a form compiled with errors.
 > Form:
 >   (CAT-9:RANDOM-MATRIX 4 5 10)
 > Compile-time error:
 >   during macroexpansion of (CAT-9:RANDOM-MATRIX 4 5 ...). Use 
*BREAK-ON-SIGNALS* to intercept.
 >  error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too 
few elements in (4 5 10) to satisfy lambda list (CAT-9::LINE-N 
CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..
 >  --------------------------------
 >  --------------------------------
 >  COLUMN-MINUS []:
 >       Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {1004625A23}>
 > Execution of a form compiled with errors.
 > Form:
 >   (CAT-9:RANDOM-MATRIX 3 4 10)
 > Compile-time error:
 >   during macroexpansion of (CAT-9:RANDOM-MATRIX 3 4 ...). Use 
*BREAK-ON-SIGNALS* to intercept.
 >  error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too 
few elements in (3 4 10) to satisfy lambda list (CAT-9::LINE-N 
CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..
 >  --------------------------------
 >  --------------------------------
 >  COLUMN-SWAP-5 []:
 >       Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {1004623313}>
 > Execution of a form compiled with errors.
 > Form:
 >   (CAT-9:RANDOM-MATRIX 4 5 10)
 > Compile-time error:
 >   during macroexpansion of (CAT-9:RANDOM-MATRIX 4 5 ...). Use 
*BREAK-ON-SIGNALS* to intercept.
 >  error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too 
few elements in (4 5 10) to satisfy lambda list (CAT-9::LINE-N 
CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..
 >  --------------------------------
 >  --------------------------------
 >  COLUMN-SWAP []:
 >       Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {10046205E3}>
 > Execution of a form compiled with errors.
 > Form:
 >   (CAT-9:RANDOM-MATRIX 3 4 10)
 > Compile-time error:
 >   during macroexpansion of (CAT-9:RANDOM-MATRIX 3 4 ...). Use 
*BREAK-ON-SIGNALS* to intercept.
 >  error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too 
few elements in (3 4 10) to satisfy lambda list (CAT-9::LINE-N 
CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..
 >  --------------------------------
 >  --------------------------------
 >  LINE-SWAP-5 []:
 >       Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {100461DEA3}>
 > Execution of a form compiled with errors.
 > Form:
 >   (CAT-9:RANDOM-MATRIX 4 5 10)
 > Compile-time error:
 >   during macroexpansion of (CAT-9:RANDOM-MATRIX 4 5 ...). Use 
*BREAK-ON-SIGNALS* to intercept.
 >  error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too 
few elements in (4 5 10) to satisfy lambda list (CAT-9::LINE-N 
CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..
 >  --------------------------------
 >  --------------------------------
 >  LINE-SWAP []:
 >       Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {100461B173}>
 > Execution of a form compiled with errors.
 > Form:
 >   (CAT-9:RANDOM-MATRIX 3 4 10)
 > Compile-time error:
 >   during macroexpansion of (CAT-9:RANDOM-MATRIX 3 4 ...). Use 
*BREAK-ON-SIGNALS* to intercept.
 >  error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too 
few elements in (3 4 10) to satisfy lambda list (CAT-9::LINE-N 
CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..
 >  --------------------------------
 >  --------------------------------
 >  COLUMN-OP-5 []:
 >       Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {1004618A63}>
 > Execution of a form compiled with errors.
 > Form:
 >   (CAT-9:RANDOM-MATRIX 4 5 10)
 > Compile-time error:
 >   during macroexpansion of (CAT-9:RANDOM-MATRIX 4 5 ...). Use 
*BREAK-ON-SIGNALS* to intercept.
 >  error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too 
few elements in (4 5 10) to satisfy lambda list (CAT-9::LINE-N 
CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..
 >  --------------------------------
 >  --------------------------------
 >  COLUMN-OP []:
 >       Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {1004615B43}>
 > Execution of a form compiled with errors.
 > Form:
 >   (CAT-9:RANDOM-MATRIX 3 4 10)
 > Compile-time error:
 >   during macroexpansion of (CAT-9:RANDOM-MATRIX 3 4 ...). Use 
*BREAK-ON-SIGNALS* to intercept.
 >  error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too 
few elements in (3 4 10) to satisfy lambda list (CAT-9::LINE-N 
CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..
 >  --------------------------------
 >  --------------------------------
 >  LINE-OP-5 []:
 >       Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {1004613433}>
 > Execution of a form compiled with errors.
 > Form:
 >   (CAT-9:RANDOM-MATRIX 4 5 10)
 > Compile-time error:
 >   during macroexpansion of (CAT-9:RANDOM-MATRIX 4 5 ...). Use 
*BREAK-ON-SIGNALS* to intercept.
 >  error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too 
few elements in (4 5 10) to satisfy lambda list (CAT-9::LINE-N 
CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..
 >  --------------------------------
 >  --------------------------------
 >  LINE-OP []:
 >       Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {1004610703}>
 > Execution of a form compiled with errors.
 > Form:
 >   (CAT-9:RANDOM-MATRIX 3 4 10)
 > Compile-time error:
 >   during macroexpansion of (CAT-9:RANDOM-MATRIX 3 4 ...). Use 
*BREAK-ON-SIGNALS* to intercept.
 >  error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too 
few elements in (3 4 10) to satisfy lambda list (CAT-9::LINE-N 
CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..
 >  --------------------------------
 >  --------------------------------
 >  CHCM-MTRX []:
 >       Unexpected Error: #<TYPE-ERROR expected-type: ARRAY datum:
 > ========== MATRIX 0 row(s) + 1 column(s) =====
 > ========== END-MATRIX>
 > The value
 > ========== MATRIX 0 row(s) + 1 column(s) =====
 > ========== END-MATRIX is not of type ARRAY..
 >  --------------------------------
 >  --------------------------------
 >  MTRX-PRDC []:
 >       Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {10045FF8F3}>
 > Execution of a form compiled with errors.
 > Form:
 >   (CAT-9:RANDOM-MATRIX 2 3 10)
 > Compile-time error:
 >   during macroexpansion of (CAT-9:RANDOM-MATRIX 2 3 ...). Use 
*BREAK-ON-SIGNALS* to intercept.
 >  error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too 
few elements in (2 3 10) to satisfy lambda list (CAT-9::LINE-N 
CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..
 >  --------------------------------
 >  --------------------------------
 >  LEFT-SUBMATRIX []:
 >       Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {10045FD1E3}>
 > Execution of a form compiled with errors.
 > Form:
 >   (CAT-9:RANDOM-MATRIX 3 4 10)
 > Compile-time error:
 >   during macroexpansion of (CAT-9:RANDOM-MATRIX 3 4 ...). Use 
*BREAK-ON-SIGNALS* to intercept.
 >  error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too 
few elements in (3 4 10) to satisfy lambda list (CAT-9::LINE-N 
CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..
 >  --------------------------------
 >  --------------------------------
 >  COPY-MTRX []:
 >       Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {10045FA533}>
 > Execution of a form compiled with errors.
 > Form:
 >   (CAT-9:RANDOM-MATRIX 3 4 10)
 > Compile-time error:
 >   during macroexpansion of (CAT-9:RANDOM-MATRIX 3 4 ...). Use 
*BREAK-ON-SIGNALS* to intercept.
 >  error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too 
few elements in (3 4 10) to satisfy lambda list (CAT-9::LINE-N 
CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..
 >  --------------------------------
 >  --------------------------------
 >  RANDOM-MATRIX []:
 >       Unexpected Error: #<SB-INT:COMPILED-PROGRAM-ERROR {10045F08B3}>
 > Execution of a form compiled with errors.
 > Form:
 >   (CAT-9:RANDOM-MATRIX 2 3 10)
 > Compile-time error:
 >   during macroexpansion of (CAT-9:RANDOM-MATRIX 2 3 ...). Use 
*BREAK-ON-SIGNALS* to intercept.
 >  error while parsing arguments to DEFMACRO CAT-9:RANDOM-MATRIX:too 
few elements in (2 3 10) to satisfy lambda list (CAT-9::LINE-N 
CAT-9::COLUMN-N CAT-9::DNST MAX): exactly 4 expected, but got 3..

**Comment by gheber** [comment]
I think the real "culprit" is the backward-compatibility breaking lambda list change from Kenzo 8 to 9:
```
(DEFUN RANDOM-MATRIX (line-n column-n max) ...)
```
becomes
```
(DEFMACRO RANDOM-MATRIX (line-n column-n dnst max) ...)
```
where `DNST` is the fraction of non-zero entries. How about something like
```
(DEFMACRO RANDOM-MATRIX (line-n column-n max &optional (dnst 1.0)) ...)
```
?
