### ISSUE TITLE
*LIST-LIST* used in Kenzo extensions

### ISSUE THREAD

**Issue by dimpase** [gheber/kenzo#15]
I notice that `*LIST-LIST*` is used in e.g. [persistent homology code](http://www.unirioja.es/cu/anromero/persistent-homology.zip), and this doesn't work with the new source layout.

**Comment by gheber** [comment]
I'm trying to separate the examples from the code that should be part of Kenzo. See 53d13214 for a first example. The biggest issue is the inadequate testing. It'll take a while to catch up with the main Kenzo source.

**Comment by gheber** [comment]
*LIST-LIST* is now an exported symbol.
