### ISSUE TITLE
TeX sources of docs?

### ISSUE THREAD

**Issue by dimpase** [gheber/kenzo#17]
IMHO we should add them, as we have permission to do so. Let know if you like me to clean them up to make them more portable.

**Comment by gheber** [comment]
That'd be great. I looked at them briefly and believed they were sound. There are a few absolute path names baked in, but nothing really "irreparable."

**Comment by dimpase** [comment]
perhaps you can add me as a collaborator on the repo, this would be easier than doing pull requests.

**Comment by gheber** [comment]
Done. Welcome!

**Comment by dimpase** [comment]
added.
