### ISSUE TITLE
Different compilers run different subsets of tests?

### ISSUE THREAD

**Issue by gheber** [gheber/kenzo#48]
Before a commit, I usually run the test suite with different compilers. I noticed that they report different numbers of checks run: CCL (805), ECL (778) and SBCL (787). All checks pass and no failures are reported. I'm not sure what's going on. Maybe they do indeed run different subsets of tests or just report differently?

**Comment by dimpase** [comment]
Well, there are compiler-specific lines of code scattered around Kenzo, could it be the reason?

**Comment by gheber** [comment]
After disabling randomly failing test (see #63) the number off tests passing is consistent across compilers: 768.
