### ISSUE TITLE
state of ipython interface

### ISSUE THREAD

**Issue by dimpase** [gheber/kenzo#64]
Could you say where you are on this? Thanks!

**Comment by gheber** [comment]
You have to install cl-jupyter (https://github.com/fredokun/cl-jupyter)
It works fine with SBCL 1.2.15 and CCL 1.10. I've created a few examples:

https://github.com/gheber/kenzo/blob/master/examples/Overview.ipynb
https://github.com/gheber/kenzo/blob/master/examples/Chapter1.ipynb
https://github.com/gheber/kenzo/blob/master/examples/Chapter2.ipynb
https://github.com/gheber/kenzo/blob/master/examples/Chapter3.ipynb

More to come. (Just got back from vacation...)
